import { describe, it } from 'vitest';

import { expectGeneratedFixtureToMatch } from './compile.support.js';

const APPLY_TEMPLATES_NESTED_MATCH_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><detail><xsl:value-of select="."/></detail></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_CHOOSE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><flagged/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_CHOOSE_NO_OTHERWISE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><flagged/></xsl:when></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_CHOOSE_MULTI_WHEN_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><flagged/></xsl:when><xsl:when test="vip"><vip/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_CHOOSE_NESTED_IF_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><xsl:if test="marker"><flagged/></xsl:if></xsl:when><xsl:otherwise><xsl:if test="vip"><vip/></xsl:if></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_CHOOSE_NESTED_CHOOSE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><xsl:choose><xsl:when test="marker"><flagged/></xsl:when><xsl:otherwise><brief/></xsl:otherwise></xsl:choose></xsl:when><xsl:otherwise><xsl:choose><xsl:when test="vip"><vip/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_APPLY_TEMPLATES_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="group"><xsl:apply-templates select="detail"/></xsl:for-each></details></item></xsl:template><xsl:template match="detail"><detail><xsl:value-of select="."/></detail></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_APPLY_TEMPLATES_DEFAULT_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="group"><xsl:apply-templates/></xsl:for-each></details></item></xsl:template><xsl:template match="detail"><detail><xsl:value-of select="."/></detail></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><detail><xsl:value-of select="."/></detail></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><flagged/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_NO_OTHERWISE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><flagged/></xsl:when></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_MULTI_WHEN_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><flagged/></xsl:when><xsl:when test="vip"><vip/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_NESTED_IF_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><xsl:if test="marker"><flagged/></xsl:if></xsl:when><xsl:otherwise><xsl:if test="vip"><vip/></xsl:if></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_NESTED_CHOOSE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><xsl:choose><xsl:when test="marker"><flagged/></xsl:when><xsl:otherwise><brief/></xsl:otherwise></xsl:choose></xsl:when><xsl:otherwise><xsl:choose><xsl:when test="vip"><vip/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_APPLY_TEMPLATES_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="group"><xsl:apply-templates select="detail"/></xsl:for-each></details></item></xsl:template><xsl:template match="detail"><detail><xsl:value-of select="."/></detail></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_APPLY_TEMPLATES_DEFAULT_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="group"><xsl:apply-templates/></xsl:for-each></details></item></xsl:template><xsl:template match="detail"><detail><xsl:value-of select="."/></detail></xsl:template></xsl:stylesheet>';

const FIXTURE_CASES = [
  { name: 'apply-templates-nested-match', path: 'apply-templates-nested-match.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-for-each', path: 'apply-templates-nested-match-for-each.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-for-each-choose', path: 'apply-templates-nested-match-for-each-choose.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_CHOOSE_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-for-each-choose-no-otherwise', path: 'apply-templates-nested-match-for-each-choose-no-otherwise.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_CHOOSE_NO_OTHERWISE_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-for-each-choose-multi-when', path: 'apply-templates-nested-match-for-each-choose-multi-when.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_CHOOSE_MULTI_WHEN_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-for-each-choose-nested-if', path: 'apply-templates-nested-match-for-each-choose-nested-if.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_CHOOSE_NESTED_IF_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-for-each-choose-nested-choose', path: 'apply-templates-nested-match-for-each-choose-nested-choose.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_CHOOSE_NESTED_CHOOSE_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-for-each-apply-templates', path: 'apply-templates-nested-match-for-each-apply-templates.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_APPLY_TEMPLATES_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-for-each-apply-templates-default', path: 'apply-templates-nested-match-for-each-apply-templates-default.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_FOR_EACH_APPLY_TEMPLATES_DEFAULT_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-default', path: 'apply-templates-nested-match-default.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-default-for-each', path: 'apply-templates-nested-match-default-for-each.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-default-for-each-choose', path: 'apply-templates-nested-match-default-for-each-choose.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-default-for-each-choose-no-otherwise', path: 'apply-templates-nested-match-default-for-each-choose-no-otherwise.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_NO_OTHERWISE_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-default-for-each-choose-multi-when', path: 'apply-templates-nested-match-default-for-each-choose-multi-when.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_MULTI_WHEN_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-default-for-each-choose-nested-if', path: 'apply-templates-nested-match-default-for-each-choose-nested-if.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_NESTED_IF_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-default-for-each-choose-nested-choose', path: 'apply-templates-nested-match-default-for-each-choose-nested-choose.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_NESTED_CHOOSE_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-default-for-each-apply-templates', path: 'apply-templates-nested-match-default-for-each-apply-templates.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_APPLY_TEMPLATES_FIXTURE_STYLESHEET },
  { name: 'apply-templates-nested-match-default-for-each-apply-templates-default', path: 'apply-templates-nested-match-default-for-each-apply-templates-default.xsl', stylesheet: APPLY_TEMPLATES_NESTED_MATCH_DEFAULT_FOR_EACH_APPLY_TEMPLATES_DEFAULT_FIXTURE_STYLESHEET },
] as const;

describe('XSLT codegen apply-templates nested-match fixtures', () => {
  for (const { name, path, stylesheet } of FIXTURE_CASES) {
    it(`matches the checked-in generated fixture for the ${name} stylesheet`, () => {
      expectGeneratedFixtureToMatch(stylesheet, path);
    });
  }
});