import { describe, it } from 'vitest';

import { expectGeneratedFixtureToMatch } from './compile.support.js';

const APPLY_TEMPLATES_DOT_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="."/></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_IF_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><xsl:if test="flag"><flagged/></xsl:if></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_FOR_EACH_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><detail><xsl:value-of select="."/></detail></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_FOR_EACH_CHOOSE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><flagged/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_FOR_EACH_CHOOSE_NO_OTHERWISE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><flagged/></xsl:when></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_FOR_EACH_CHOOSE_MULTI_WHEN_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><flagged/></xsl:when><xsl:when test="vip"><vip/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_FOR_EACH_CHOOSE_NESTED_IF_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><xsl:if test="marker"><flagged/></xsl:if></xsl:when><xsl:otherwise><xsl:if test="vip"><vip/></xsl:if></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_FOR_EACH_CHOOSE_NESTED_CHOOSE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><xsl:choose><xsl:when test="marker"><flagged/></xsl:when><xsl:otherwise><brief/></xsl:otherwise></xsl:choose></xsl:when><xsl:otherwise><xsl:choose><xsl:when test="vip"><vip/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_FOR_EACH_APPLY_TEMPLATES_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><details><xsl:for-each select="group"><xsl:apply-templates select="detail"/></xsl:for-each></details></item></xsl:template><xsl:template match="detail"><detail><xsl:value-of select="."/></detail></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_FOR_EACH_APPLY_TEMPLATES_DEFAULT_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><details><xsl:for-each select="group"><xsl:apply-templates/></xsl:for-each></details></item></xsl:template><xsl:template match="detail"><detail><xsl:value-of select="."/></detail></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_CHOOSE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><xsl:choose><xsl:when test="flag"><flagged/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_CHOOSE_NO_OTHERWISE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><xsl:choose><xsl:when test="flag"><flagged/></xsl:when></xsl:choose></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_CHOOSE_MULTI_WHEN_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><xsl:choose><xsl:when test="flag"><flagged/></xsl:when><xsl:when test="vip"><vip/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_CHOOSE_NESTED_IF_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><xsl:choose><xsl:when test="flag"><xsl:if test="detail"><flagged/></xsl:if></xsl:when><xsl:otherwise><xsl:if test="vip"><vip/></xsl:if></xsl:otherwise></xsl:choose></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_CHOOSE_NESTED_CHOOSE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><xsl:choose><xsl:when test="flag"><xsl:choose><xsl:when test="detail"><flagged/></xsl:when><xsl:otherwise><brief/></xsl:otherwise></xsl:choose></xsl:when><xsl:otherwise><xsl:choose><xsl:when test="vip"><vip/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:otherwise></xsl:choose></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_APPLY_TEMPLATES_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><details><xsl:apply-templates select="detail"/></details></item></xsl:template><xsl:template match="detail"><detail><xsl:value-of select="."/></detail></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_CHILD_APPLY_TEMPLATES_DEFAULT_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/item"/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="name"/><details><xsl:apply-templates/></details></item></xsl:template><xsl:template match="detail"><detail><xsl:value-of select="."/></detail></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_DEFAULT_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="item"><item><xsl:value-of select="."/></item></xsl:template></xsl:stylesheet>';

const FIXTURE_CASES = [
  { name: 'apply-templates-dot', path: 'apply-templates-dot.xsl', stylesheet: APPLY_TEMPLATES_DOT_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-for-each', path: 'apply-templates-child-for-each.xsl', stylesheet: APPLY_TEMPLATES_CHILD_FOR_EACH_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-for-each-choose', path: 'apply-templates-child-for-each-choose.xsl', stylesheet: APPLY_TEMPLATES_CHILD_FOR_EACH_CHOOSE_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-for-each-choose-no-otherwise', path: 'apply-templates-child-for-each-choose-no-otherwise.xsl', stylesheet: APPLY_TEMPLATES_CHILD_FOR_EACH_CHOOSE_NO_OTHERWISE_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-for-each-choose-multi-when', path: 'apply-templates-child-for-each-choose-multi-when.xsl', stylesheet: APPLY_TEMPLATES_CHILD_FOR_EACH_CHOOSE_MULTI_WHEN_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-for-each-choose-nested-if', path: 'apply-templates-child-for-each-choose-nested-if.xsl', stylesheet: APPLY_TEMPLATES_CHILD_FOR_EACH_CHOOSE_NESTED_IF_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-for-each-choose-nested-choose', path: 'apply-templates-child-for-each-choose-nested-choose.xsl', stylesheet: APPLY_TEMPLATES_CHILD_FOR_EACH_CHOOSE_NESTED_CHOOSE_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-for-each-apply-templates', path: 'apply-templates-child-for-each-apply-templates.xsl', stylesheet: APPLY_TEMPLATES_CHILD_FOR_EACH_APPLY_TEMPLATES_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-for-each-apply-templates-default', path: 'apply-templates-child-for-each-apply-templates-default.xsl', stylesheet: APPLY_TEMPLATES_CHILD_FOR_EACH_APPLY_TEMPLATES_DEFAULT_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-if', path: 'apply-templates-child-if.xsl', stylesheet: APPLY_TEMPLATES_CHILD_IF_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-choose', path: 'apply-templates-child-choose.xsl', stylesheet: APPLY_TEMPLATES_CHILD_CHOOSE_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-choose-no-otherwise', path: 'apply-templates-child-choose-no-otherwise.xsl', stylesheet: APPLY_TEMPLATES_CHILD_CHOOSE_NO_OTHERWISE_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-choose-multi-when', path: 'apply-templates-child-choose-multi-when.xsl', stylesheet: APPLY_TEMPLATES_CHILD_CHOOSE_MULTI_WHEN_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-choose-nested-if', path: 'apply-templates-child-choose-nested-if.xsl', stylesheet: APPLY_TEMPLATES_CHILD_CHOOSE_NESTED_IF_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-choose-nested-choose', path: 'apply-templates-child-choose-nested-choose.xsl', stylesheet: APPLY_TEMPLATES_CHILD_CHOOSE_NESTED_CHOOSE_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-apply-templates', path: 'apply-templates-child-apply-templates.xsl', stylesheet: APPLY_TEMPLATES_CHILD_APPLY_TEMPLATES_FIXTURE_STYLESHEET },
  { name: 'apply-templates-child-apply-templates-default', path: 'apply-templates-child-apply-templates-default.xsl', stylesheet: APPLY_TEMPLATES_CHILD_APPLY_TEMPLATES_DEFAULT_FIXTURE_STYLESHEET },
  { name: 'apply-templates-default', path: 'apply-templates-default.xsl', stylesheet: APPLY_TEMPLATES_DEFAULT_FIXTURE_STYLESHEET },
] as const;

describe('XSLT codegen apply-templates tail fixtures', () => {
  for (const { name, path, stylesheet } of FIXTURE_CASES) {
    it(`matches the checked-in generated fixture for the ${name} stylesheet`, () => {
      expectGeneratedFixtureToMatch(stylesheet, path);
    });
  }
});