import { describe, it } from 'vitest';

import { expectRuntimeModuleToMatchInterpreter } from './compile.support.js';

const APPLY_TEMPLATES_ABSOLUTE_MATCH_DEFAULT_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="/root/item"><item><xsl:value-of select="name"/></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><detail><xsl:value-of select="."/></detail></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><flagged/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_NO_OTHERWISE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><flagged/></xsl:when></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_MULTI_WHEN_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><flagged/></xsl:when><xsl:when test="vip"><vip/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_NESTED_IF_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><xsl:if test="marker"><flagged/></xsl:if></xsl:when><xsl:otherwise><xsl:if test="vip"><vip/></xsl:if></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_NESTED_CHOOSE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><xsl:choose><xsl:when test="marker"><flagged/></xsl:when><xsl:otherwise><brief/></xsl:otherwise></xsl:choose></xsl:when><xsl:otherwise><xsl:choose><xsl:when test="vip"><vip/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_APPLY_TEMPLATES_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="group"><xsl:apply-templates select="detail"/></xsl:for-each></details></item></xsl:template><xsl:template match="detail"><detail><xsl:value-of select="."/></detail></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_APPLY_TEMPLATES_DEFAULT_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="group"><xsl:apply-templates/></xsl:for-each></details></item></xsl:template><xsl:template match="detail"><detail><xsl:value-of select="."/></detail></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><detail><xsl:value-of select="."/></detail></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_CHOOSE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><flagged/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_CHOOSE_NO_OTHERWISE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><flagged/></xsl:when></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_CHOOSE_MULTI_WHEN_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><flagged/></xsl:when><xsl:when test="vip"><vip/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_CHOOSE_NESTED_IF_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><xsl:if test="marker"><flagged/></xsl:if></xsl:when><xsl:otherwise><xsl:if test="vip"><vip/></xsl:if></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_CHOOSE_NESTED_CHOOSE_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="detail"><xsl:choose><xsl:when test="flag"><xsl:choose><xsl:when test="marker"><flagged/></xsl:when><xsl:otherwise><brief/></xsl:otherwise></xsl:choose></xsl:when><xsl:otherwise><xsl:choose><xsl:when test="vip"><vip/></xsl:when><xsl:otherwise><plain/></xsl:otherwise></xsl:choose></xsl:otherwise></xsl:choose></xsl:for-each></details></item></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_APPLY_TEMPLATES_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="group"><xsl:apply-templates select="detail"/></xsl:for-each></details></item></xsl:template><xsl:template match="detail"><detail><xsl:value-of select="."/></detail></xsl:template></xsl:stylesheet>';
const APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_APPLY_TEMPLATES_DEFAULT_FIXTURE_STYLESHEET = '<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:template match="/"><items><xsl:apply-templates select="/root/section/item"/></items></xsl:template><xsl:template match="/root/section/item"><item><xsl:value-of select="name"/><details><xsl:for-each select="group"><xsl:apply-templates/></xsl:for-each></details></item></xsl:template><xsl:template match="detail"><detail><xsl:value-of select="."/></detail></xsl:template></xsl:stylesheet>';

const RUNTIME_CASES = [
  { name: 'apply-templates-absolute-match-default', path: 'apply-templates-absolute-match-default.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_MATCH_DEFAULT_FIXTURE_STYLESHEET, sourceXml: '<root><item><name>apple</name></item><note>carry</note><group><item><name>skip</name></item></group><item><name>pear</name></item></root>' },
  { name: 'apply-templates-absolute-nested-match', path: 'apply-templates-absolute-nested-match.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FIXTURE_STYLESHEET, sourceXml: '<root><section><item><name>apple</name></item></section><section><item><name>pear</name></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-default', path: 'apply-templates-absolute-nested-match-default.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FIXTURE_STYLESHEET, sourceXml: '<root><item><name>skip</name></item><section><item><name>apple</name></item></section><group><item><name>skip-too</name></item></group><section><item><name>pear</name></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-default-for-each', path: 'apply-templates-absolute-nested-match-default-for-each.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_FIXTURE_STYLESHEET, sourceXml: '<root><item><name>skip</name></item><section><item><name>apple</name><detail>fresh</detail><detail>green</detail></item></section><group><item><name>skip-too</name></item></group><section><item><name>pear</name><detail>ripe</detail></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-default-for-each-choose', path: 'apply-templates-absolute-nested-match-default-for-each-choose.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_FIXTURE_STYLESHEET, sourceXml: '<root><item><name>skip</name></item><section><item><name>apple</name><detail><flag/></detail><detail/></item></section><section><item><name>pear</name><detail/></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-default-for-each-choose-no-otherwise', path: 'apply-templates-absolute-nested-match-default-for-each-choose-no-otherwise.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_NO_OTHERWISE_FIXTURE_STYLESHEET, sourceXml: '<root><item><name>skip</name></item><section><item><name>apple</name><detail><flag/></detail><detail/></item></section><section><item><name>pear</name><detail/></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-default-for-each-choose-multi-when', path: 'apply-templates-absolute-nested-match-default-for-each-choose-multi-when.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_MULTI_WHEN_FIXTURE_STYLESHEET, sourceXml: '<root><item><name>skip</name></item><section><item><name>apple</name><detail><flag/></detail><detail><vip/></detail><detail/></item></section><section><item><name>pear</name><detail><vip/></detail></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-default-for-each-choose-nested-if', path: 'apply-templates-absolute-nested-match-default-for-each-choose-nested-if.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_NESTED_IF_FIXTURE_STYLESHEET, sourceXml: '<root><item><name>skip</name></item><section><item><name>apple</name><detail><flag/><marker/></detail><detail><vip/></detail><detail><flag/></detail></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-default-for-each-choose-nested-choose', path: 'apply-templates-absolute-nested-match-default-for-each-choose-nested-choose.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_CHOOSE_NESTED_CHOOSE_FIXTURE_STYLESHEET, sourceXml: '<root><item><name>skip</name></item><section><item><name>apple</name><detail><flag/><marker/></detail><detail><flag/></detail><detail><vip/></detail><detail/></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-default-for-each-apply-templates', path: 'apply-templates-absolute-nested-match-default-for-each-apply-templates.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_APPLY_TEMPLATES_FIXTURE_STYLESHEET, sourceXml: '<root><section><item><name>apple</name><group><detail>fresh</detail><detail>green</detail></group></item></section><section><item><name>pear</name><group><detail>ripe</detail></group></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-default-for-each-apply-templates-default', path: 'apply-templates-absolute-nested-match-default-for-each-apply-templates-default.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_DEFAULT_FOR_EACH_APPLY_TEMPLATES_DEFAULT_FIXTURE_STYLESHEET, sourceXml: '<root><section><item><name>apple</name><group><detail>fresh</detail><detail>green</detail></group></item></section><section><item><name>pear</name><group><detail>ripe</detail></group></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-for-each', path: 'apply-templates-absolute-nested-match-for-each.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_FIXTURE_STYLESHEET, sourceXml: '<root><section><item><name>apple</name><detail>fresh</detail><detail>green</detail></item><item><name>pear</name><detail>ripe</detail></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-for-each-choose', path: 'apply-templates-absolute-nested-match-for-each-choose.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_CHOOSE_FIXTURE_STYLESHEET, sourceXml: '<root><section><item><name>apple</name><detail><flag/></detail><detail/></item><item><name>pear</name><detail/></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-for-each-choose-no-otherwise', path: 'apply-templates-absolute-nested-match-for-each-choose-no-otherwise.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_CHOOSE_NO_OTHERWISE_FIXTURE_STYLESHEET, sourceXml: '<root><section><item><name>apple</name><detail><flag/></detail><detail/></item><item><name>pear</name><detail/></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-for-each-choose-multi-when', path: 'apply-templates-absolute-nested-match-for-each-choose-multi-when.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_CHOOSE_MULTI_WHEN_FIXTURE_STYLESHEET, sourceXml: '<root><section><item><name>apple</name><detail><flag/></detail><detail><vip/></detail><detail/></item><item><name>pear</name><detail><vip/></detail></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-for-each-choose-nested-if', path: 'apply-templates-absolute-nested-match-for-each-choose-nested-if.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_CHOOSE_NESTED_IF_FIXTURE_STYLESHEET, sourceXml: '<root><section><item><name>apple</name><detail><flag/><marker/></detail><detail><vip/></detail><detail><flag/></detail></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-for-each-choose-nested-choose', path: 'apply-templates-absolute-nested-match-for-each-choose-nested-choose.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_CHOOSE_NESTED_CHOOSE_FIXTURE_STYLESHEET, sourceXml: '<root><section><item><name>apple</name><detail><flag/><marker/></detail><detail><flag/></detail><detail><vip/></detail><detail/></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-for-each-apply-templates', path: 'apply-templates-absolute-nested-match-for-each-apply-templates.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_APPLY_TEMPLATES_FIXTURE_STYLESHEET, sourceXml: '<root><section><item><name>apple</name><group><detail>fresh</detail><detail>green</detail></group></item></section></root>' },
  { name: 'apply-templates-absolute-nested-match-for-each-apply-templates-default', path: 'apply-templates-absolute-nested-match-for-each-apply-templates-default.xsl', stylesheet: APPLY_TEMPLATES_ABSOLUTE_NESTED_MATCH_FOR_EACH_APPLY_TEMPLATES_DEFAULT_FIXTURE_STYLESHEET, sourceXml: '<root><section><item><name>apple</name><group><detail>fresh</detail><detail>green</detail></group></item></section></root>' },
] as const;

describe('XSLT codegen apply-templates absolute default and nested runtime surface', () => {
  for (const { name, path, stylesheet, sourceXml } of RUNTIME_CASES) {
    it(`executes the ${name} stylesheet through the runtime surface`, () => {
      expectRuntimeModuleToMatchInterpreter(stylesheet, path, sourceXml);
    });
  }
});