<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <RestoreSources>$(RestoreSources);$(MSBuildThisFileDirectory)..\Weaver.Build\artifacts</RestoreSources>
    <WeaverNode>node</WeaverNode>
    <WeaverEmit>bundle</WeaverEmit>
    <!-- Enable failing the build on diagnostics for this test -->
    <WeaverFailOnDiagnostics>true</WeaverFailOnDiagnostics>
    <WeaverCopyToOutput>false</WeaverCopyToOutput>
    <WeaverOutputDir>$(MSBuildProjectDirectory)/weaver-out/</WeaverOutputDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Weaver.Build" Version="0.0.1" />
    <WeaverStylesheet Include="Stylesheets/semantic-error.xsl" />
  </ItemGroup>
</Project>
