export {
  compileStylesheetArtifacts,
  compileStylesheetArtifactsFromFile,
  summarizeComposedStylesheetFromFile,
  compileStylesheetToDts,
  compileStylesheetToTs,
  type ComposedStylesheetDuplicateSummary,
  type ComposedStylesheetSummary,
  type CompileIrStats,
  type CompileMemoryUsageSnapshot,
  type CompilePerformancePhase,
  type CompilePerformanceProfile,
  type CompileStylesheetArtifacts,
  type CompileStylesheetArtifactsFromFileOptions,
  type CompileStylesheetToTsOptions,
} from './processor/compile.js';
