export {
  assertValidDiagnostic,
  compareDiagnostics,
  diagnosticReportFromError,
  formatDiagnostic,
  formatDiagnostics,
  projectDiagnosticReport,
  projectDiagnosticReports,
  renderDiagnosticError,
  sortDiagnostics,
  type DiagnosticCategory,
  type DiagnosticDetail,
  type DiagnosticFrame,
  type DiagnosticPhase,
  type DiagnosticReport,
  type DiagnosticSeverity,
  type DiagnosticSuggestion,
  type JsonDiagnosticReport,
  type RelatedSpan,
  type SourceSpan,
} from './diagnostics/index.js';